In [3]:
import re 
import pandas as pd
import numpy as np
import nltk

In [69]:
data_r= "C:\\Users\\om sai\\Downloads\\ml-1m\\ratings.dat"
data_ratings= pd.read_csv(data_r,sep="::",names=["user_id","movie_id","rating","time"])
data_m= "C:\\Users\\om sai\\Downloads\\ml-1m\\movies.dat"
data_movies= pd.read_csv(data_m,sep="::",names=["movie_id","title","genre"])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


In [70]:
data_ratings.drop(columns=['time'],inplace=True)
data_ratings.head()

user_id  movie_id  rating
0        1      1193       5
1        1       661       3
2        1       914       3
3        1      3408       4
4        1      2355       5

In [97]:
data_movies.head()
movie_df=data_movies

In [72]:
# example 
import numpy as np
from scipy.sparse.linalg import svds
from sklearn.metrics.pairwise import cosine_similarity

In [73]:
a= [[1,2,3],[4,5,6],[7,8,9]]

In [74]:
u,s,v =np.linalg.svd(a)

In [75]:
u

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [76]:
s

array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16])

In [77]:
v

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])

In [78]:
s=np.diag(s)

In [79]:
s

array([[1.68481034e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.06836951e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.33475287e-16]])

In [80]:
np.dot(u,np.dot(s,v))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [81]:
merged_df = pd.merge(data_ratings,data_movies,on="movie_id")

In [82]:
pivot_ratings_df = data_ratings.pivot_table(index='user_id',columns='movie_id',values='rating',
                                            fill_value=0)

In [83]:
pivot_ratings_df.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1            5     0     0     0     0     0     0     0     0     0  ...   
2            0     0     0     0     0     0     0     0     0     0  ...   
3            0     0     0     0     0     0     0     0     0     0  ...   
4            0     0     0     0     0     0     0     0     0     0  ...   
5            0     0     0     0     0     2     0     0     0     0  ...   

movie_id  3943  3944  3945  3946  3947  3948  3949  3950  3951  3952  
user_id                                                               
1            0     0     0     0     0     0     0     0     0     0  
2            0     0     0     0     0     0     0     0     0     0  
3            0     0     0     0     0     0     0     0     0     0  
4            0     0     0     0     0     0     0     0     0     0  
5            0     0     0     0     0     0     0     0     0     0  

[5 rows x 3706 columns]

In [84]:
pivot_ratings_df.shape

(6040, 3706)

In [85]:
movie_id_list =list(pivot_ratings_df.columns)

In [86]:
pivot_ratings_df.shape

(6040, 3706)

In [87]:
matrix = pivot_ratings_df.values.astype(float)

In [88]:
u,s,vt= svds(matrix,k=10)

In [89]:
print(u)

[[-1.32554344e-02 -1.89421895e-02  4.36062120e-03 ... -2.67140840e-03
   1.64550698e-03 -4.71785773e-03]
 [ 8.66394079e-04  1.45177584e-03 -7.20286579e-03 ... -3.82152933e-04
  -2.69781903e-03 -9.28855590e-03]
 [-1.42217207e-03  2.92755311e-03  5.19842475e-03 ...  3.34366161e-03
  -3.34291508e-03 -5.01017861e-03]
 ...
 [-7.53557332e-05  1.43491727e-03 -1.26431692e-03 ...  1.18789245e-04
   1.81338730e-03 -1.38885083e-03]
 [-1.25707572e-02  1.37237869e-02  1.21390991e-02 ...  1.07122502e-02
   1.87647017e-02 -7.00792837e-03]
 [-2.83112003e-03 -4.67067414e-03 -1.92062499e-02 ...  3.04316280e-03
   4.08024430e-02 -1.89610238e-02]]


In [90]:
v=vt.T

In [91]:
v.shape

(3706, 10)

In [92]:
item_themes_df= pd.DataFrame(v)

In [93]:
item_themes_df['movie_id']=movie_id_list

In [94]:
item_themes_df.head()

0         1         2         3         4         5         6  \
0 -0.088299  0.015144  0.021400 -0.000089  0.017823 -0.124778  0.004862   
1 -0.028098 -0.013527  0.003375 -0.033662 -0.005091 -0.009581 -0.031090   
2  0.003022  0.005730  0.018735 -0.006066  0.005460 -0.005833 -0.027143   
3  0.003311 -0.004117 -0.005805 -0.005657  0.001291  0.002628 -0.015072   
4 -0.000338  0.004786  0.013983 -0.004920  0.007189 -0.004311 -0.028885   

          7         8         9  movie_id  
0 -0.030165 -0.020940 -0.070137         1  
1  0.010189 -0.029792 -0.023544         2  
2 -0.012572 -0.016704 -0.013766         3  
3 -0.012356 -0.002963 -0.005323         4  
4 -0.012475 -0.013489 -0.009717         5

In [98]:
def recommend(item_themes_df,movie_id_input):
    item_themes_df['movie_id']=movie_id_list
    vec1= item_themes_df[item_themes_df['movie_id']==movie_id_input]
    vec1=vec1.drop(columns=['movie_id'])
    cosine_sim_list=[]
    for id in movie_id_list:
        vec2 =item_themes_df [item_themes_df['movie_id']==id].drop(columns=['movie_id'])
        sim= cosine_similarity(vec1,vec2)[0][0]
        cosine_sim_list.append([id,sim])
    sorted_list = sorted(cosine_sim_list,key=lambda x : x[1],reverse=True)[0:20]
    top_indices =[idx for idx,sim in sorted_list]
    return movie_df[movie_df['movie_id'].isin(top_indices)]

In [100]:
recommend(item_themes_df,124)

movie_id                                           title  \
122        124  Star Maker, The (Uomo delle stelle, L') (1995)   
226        229                     Death and the Maiden (1994)   
242        245                        Glass Shield, The (1994)   
265        268                            Little Odessa (1994)   
317        320                                   Suture (1993)   
331        335                          Underneath, The (1995)   
722        731                       Heaven's Prisoners (1996)   
796        806                         American Buffalo (1996)   
872        884                            Sweet Nothing (1995)   
981        993                                 Infinity (1996)   
984        997                                   Caught (1996)   
1474      1508                                Traveller (1997)   
1605      1651                  Telling Lies in America (1997)   
1775      1844                               Live Flesh (1997)   
2198      2267                          Mortal Thoughts (1991)   
2214      2283                      Sheltering Sky, The (1990)   
2356      2425                             General, The (1998)   
2514      2583                         Cookie's Fortune (1999)   
2804      2873                       Lulu on the Bridge (1998)   
3449      3518                     End of Violence, The (1997)   

                      genre  
122                   Drama  
226          Drama|Thriller  
242             Crime|Drama  
265                   Drama  
317      Film-Noir|Thriller  
331        Mystery|Thriller  
722        Mystery|Thriller  
796                   Drama  
872                   Drama  
981                   Drama  
984          Drama|Thriller  
1474                  Drama  
1605                  Drama  
1775                  Drama  
2198       Mystery|Thriller  
2214                  Drama  
2356                  Crime  
2514                Mystery  
2804  Drama|Mystery|Romance  
3449         Drama|Thriller